export default{
REQUEST_CART_API:"REQUEST_CART_API",
SUCCESS_API_REQUEST:"SUCCESS_API_REQUEST",
INSERT_CARTITEM_API:"INSERT_CARTITEM_API",
CHANGE_FETCHING:"CHANGE_FETCHING",
REMOVE_CART_ITEM:"REMOVE_CART_ITEM",
REMOVE_CART_ITEM_SUCCESS:"REMOVE_CART_ITEM_SUCCESS"
}