export const Message = {
  inputRequired: "All input is required!",
  invalid: "UserName with this password is not found!",
  tokenRequired: "A token is required for authentication!",
  registered: "Congratulation You are Sucessfully Registered! 💫",
  unregister: "Sorry, User is not Successfully Register. ",
  blogSaved: "Your Blog is sucessfully Saved. ",
  errorPostBlog: "Sorry, your Blog is not Saved ",
  unFetch: "Cannot fetch blogs",
  notFound:"Blog with this userID is not Present",
  Deleted: "Blog is already deleted or not Present!",
  blogDeleted: "Sucessfully Deleted!",
  notDeleted: "Sorry, your blog is not deleted!",
  updated: "Sucessfully Updated",
  cannotUpdate:"Sorry your blog is not sucessfully updated",
  welcome: "Welcome to Your Daily Blogging Account 🙏🏻",
  unlogged:"Sorry,you are not login in your Blogging Account",
  errUploading:"'Please upload a file with extension png OR jpg OR jpeg'",
  bookDetails: "Congratulation Your Book Details are sucessfully Save",
  bookDetailsDeleted:"Your Book Details is sucessfully Deleted",
  cannotEdit:"You cannot edit someone else blog",
  blogNotFound:'Blog with this BlogID is not Present',
  cannotDeleteElse:'You cannot Delete someone else blog',
  bookNotPresent: 'No Book Present with this book ID',
  bookNotDeleted: "You cannot change Someone else book review",
  bookEdited: "Your changes are recorded"
 }